### ISSUE TITLE
Python Agent - Error during keyspace measure

### ISSUE THREAD

**Issue by silentbreaksec** [s3inlc/hashtopolis-agent#27]
Running the latest Hashtopolis and just converted to the Python client. I'm getting an error when assigning a new task. 

`Got cracker binary type hashcat
./OpenCL/: No such file or directory

Error during keyspace measure
./OpenCL/: No such file or directory

Error during keyspace measure
./OpenCL/: No such file or directory`

It obviously can't find the OpenCL directory. The error just repeats. It's worth noting the OpenCL directory exists in ".\crackers\1\OpenCL" so the I don't think the Python agent is changing the current working directory to where "hashcat64.exe" actually resides (i.e. ".\crackers\1\").

![2018-03-05_10-08-01](https://user-images.githubusercontent.com/7194249/36989000-a367013c-205d-11e8-8458-7e00781b0d5d.jpg)

**Comment by silentbreaksec** [comment]
I'm running Hashcat 4.1.0 which I see isn't supported in the Python agent in Windows. I'm guessing this is what's causing the error.

**Comment by hops** [comment]
Yes, hashcat 4.1.0 doesn't work on Windows together with hashtopolis.
We are aware of this issue and are in contact with the hashcat developers to resolve this issue.

**Comment by winxp5421** [comment]
I am going to group this issue together with issue number #329 on the server repo. 
Please look there for further updates. Thanks for reporting. 

https://github.com/s3inlc/hashtopolis/issues/329
