### ISSUE TITLE
Python Agent in Windows - no attribute os.setsid

### ISSUE THREAD

**Issue by silentbreaksec** [s3inlc/hashtopolis-agent#28]
I'm running the Python agent in Windows. When receiving tasking, the agent crashes with the error below. Obviously the 'os' module doesn't have 'setsid' in Windows. 

`Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "hashtopolis.zip\__main__.py", line 125, in <module>
  File "hashtopolis.zip\__main__.py", line 119, in loop
  File "hashtopolis.zip\htpclient\hashcat_cracker.py", line 50, in run_chunk
AttributeError: module 'os' has no attribute 'setsid'`

![2018-03-06_9-00-28](https://user-images.githubusercontent.com/7194249/37043121-1b1fbb8c-211d-11e8-84f0-c555933e1f53.jpg)

**Comment by s3inlc** [comment]
Thanks for the report, we will take care of this.

**Comment by s3inlc** [comment]
Please try with running from the python-fixes branch (https://github.com/s3inlc/hashtopolis-agent/tree/python-fixes). This should resolve the kill issue on windows.

**Comment by silentbreaksec** [comment]
Hmm...not seeing that branch and getting a 404 on your link.

**Comment by s3inlc** [comment]
Sorry, forgot to update this comment. It's merged into master, so you can just pull there.

**Comment by silentbreaksec** [comment]
Yep, that fixed it. Thanks!
