### ISSUE TITLE
C# Agent - Empty string for success check error

### ISSUE THREAD

**Issue by silentbreaksec** [s3inlc/hashtopolis-agent#29]
I'm using version 0.50.9 of the C# agent. When connecting to Hashtopolis, it errors with output below. The Python agent connects to the server which leads me to believe it's an issue with Hashtopolis. Note I'm using HTTP, not HTTPS. We're using it internally so the cert isn't signed/trusted even though I added the root CA cert it to the trusted root CA store in Windows...a problem for another day!

![aaa](https://user-images.githubusercontent.com/7194249/37043520-0d241770-211e-11e8-83c5-045305302249.jpg)

**Comment by s3inlc** [comment]
Can you please run the same with debug active? By running `hashtopolis.exe -d`

Most likely there is a problem with the url itself.

**Comment by silentbreaksec** [comment]
I had to add /api/server.php to the URL and now it seems to be working. Thanks for the help!

![image](https://user-images.githubusercontent.com/7194249/37057548-f7e77efc-2144-11e8-908d-337cdbaf60ce.png)

**Comment by s3inlc** [comment]
Glad you were able to sort it out. The link to register an agent is also provided on the new agent page ;)
