### ISSUE TITLE
charp Agent doesn't find hashcat-Binary (Win&Lin)

### ISSUE THREAD

**Issue by Lannert** [s3inlc/hashtopolis-agent#30]
The agent crashes after starting because he does not find the hashcat-Binary in the unpacked archive. The agent looks for hashcat.bin but there are only hashcat32.bin and hashcat64.bin.  Providing a copied hashcat64.bin to hashcat.bin in the archive works for the meantime.
Same behaviour within Windows: searches hashcat.exe and not hashcat32.exe/hashcat64.exe.

**Comment by s3inlc** [comment]
Currently the csharp binary does not look if the agent is 32/64bit, so you have to manually enforce this by giving `hashcat64` as basename on the cracker binary on the server.
The csharp agent will be fixed soon regarding this.

**Comment by Lannert** [comment]
Thank you.
