### ISSUE TITLE
Stuck on "Downloading" behind proxy

### ISSUE THREAD

**Issue by ninijay** [s3inlc/hashtopolis-agent#36]
Hey guys :)

I like the idea of your tool and would like to use it in our enterprise cracker-host.
Whenever I try to install the python agent on our cracking device it get's stuck on "Downloading"

![image](https://user-images.githubusercontent.com/6756364/41237452-cb8f0a78-6d93-11e8-8b21-d04444328780.png)

Info:

Agent and Server run behind proxy.

**Agent Host**
* OS: Ubuntu 16.04 Server LTS
* Hashcat already installed
* python and all depenencies installed

**Server Host**
* OS: Ubuntu 16.04 Server LTS
* Installation of hashtopolis works fine
* added newest binary from hashcat website
![image](https://user-images.githubusercontent.com/6756364/41237551-13152990-6d94-11e8-99b9-8360201f54b5.png)

The Server and Agent run on the same host, I hope this doesn't cause a problem.

The communication between them seems to be working, just downloading the binaries doesn't.
![image](https://user-images.githubusercontent.com/6756364/41237619-4b2794f8-6d94-11e8-8090-64319acfcca9.png)

Is there an option to add a proxy for the download?

**Comment by winxp5421** [comment]
A simple way to do this is to host the binary on the server. Place the hashcat.7z in <webroot>/static/hashcat.7z
Add a new cracker binary with the URL reflecting the path.

As far as I am aware the agent does not support proxy connections. (This is something that probably should be added)

**Comment by ninijay** [comment]
An option to add pre-installed binaries would also be nice, or create symlinks into director "crackers" which I also tried:

 in dir `./crackers`
![image](https://user-images.githubusercontent.com/6756364/41238290-dcfc4ae4-6d95-11e8-8cc5-77233ba338c6.png)

**Comment by ninijay** [comment]
@winxp5421 thanks for the fast response, I'll try it when I'm back at work tomorrow :)

**Comment by winxp5421** [comment]
One of the issues that we have to consider with "pre-installed" binaries.
How do we handle this on the server side? ( in regards to what version is it using and which binary group should the pre-installed get work from )
How do we handle version control?
How do we handle when to push updates / new binaries to the agent? ( especially if we don't have this info server side)

Personally, it's just easier to handle binary management server side. Mainly because at the end of the day HtP is meant to handle most agent configurations without having ssh or the need to do updates, etc. manually.

**Comment by winxp5421** [comment]
I also would like to thank you for being thorough and descriptive in your issue. Its greatly appreciated.

**Comment by ninijay** [comment]
I tried to fix this issue as mentioned, by providing the binary via /static/hashcat.7z but am still stuck at "Downloading". Is it maybe a bug in the downloading screen, that I don't see any progress?

**Comment by s3inlc** [comment]
Can you run it with the debug enabled, maybe this helps to find the problem.
Just add `"debug": true` to the config.json file.

**Comment by ninijay** [comment]
![image](https://user-images.githubusercontent.com/6756364/41279307-5ea75566-6e2c-11e8-9e7b-1951d78a1892.png)

**Comment by ninijay** [comment]
Token and hostname have been removed from the output:

```
{'token': '<token>', 'action': 'getTask'}
Starting new HTTP connection (1): <host>
"POST /api/server.php HTTP/1.1" 200 94
b'{"action":"getTask","response":"SUCCESS","taskId":null,"reason":"No suitable task available!"}'
No task available!
```

Meanwhile on the host:
![image](https://user-images.githubusercontent.com/6756364/41279370-999a47c8-6e2c-11e8-9fdd-cc626b9998a2.png)
and
![image](https://user-images.githubusercontent.com/6756364/41279408-b2016440-6e2c-11e8-8e46-92ca84cc52e6.png)

**Comment by s3inlc** [comment]
Just in case this was not clear. To make Hashtopolis assigning tasks automatically to agents, the priority of the task needs to be higher than zero.
Glad you were able to solve it.
